"""Add image_url to deals table

Revision ID: a65c7f948839
Revises: 5d46109e9e17
Create Date: 2025-12-22 22:13:12.319671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65c7f948839'
down_revision: Union[str, None] = '5d46109e9e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'image_url')
    # ### end Alembic commands ###
