export const SAMPLE_DEALS = [
  {
    id: 1,
    restaurant_name: "Drake's Dealership",
    deal_description:
      "Enjoy 50% off all draft beers during happy hour. Great selection of local craft beers from Oakland breweries.",
    original_price: 8.0,
    deal_price: 4.0,
    schedule: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      start_time: "15:00",
      end_time: "18:00",
    },
    vote_count: 42,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx1",
    created_by: "anonymous",
    created_at: "2025-01-08T10:00:00",
    location: { lat: 37.7955, lng: -122.273 },
    image_url: "/craft-beer-bar-interior-with-taps.jpg",
    address: "2325 Broadway, Oakland, CA 94612",
    neighborhood: "Jack London Square",
    phone: "(510) 568-2739",
  },
  {
    id: 2,
    restaurant_name: "Lost & Found",
    deal_description:
      "All appetizers just $5 and signature cocktails $6. Perfect spot to unwind after work with a great view of Lake Merritt.",
    original_price: 12.0,
    deal_price: 5.0,
    schedule: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      start_time: "16:00",
      end_time: "19:00",
    },
    vote_count: 38,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx2",
    created_by: "anonymous",
    created_at: "2025-01-07T14:30:00",
    location: { lat: 37.8072, lng: -122.2654 },
    image_url: "/cocktails-on-bar-with-lake-view.jpg",
    address: "2040 Lake Park Ave, Oakland, CA 94606",
    neighborhood: "Lake Merritt",
    phone: "(510) 763-2040",
  },
  {
    id: 3,
    restaurant_name: "The Kebabery",
    deal_description: "Fresh oysters for just $1 each, all day every day. Pair with their excellent wine selection.",
    original_price: 3.0,
    deal_price: 1.0,
    schedule: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      start_time: "11:00",
      end_time: "22:00",
    },
    vote_count: 56,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx3",
    created_by: "anonymous",
    created_at: "2025-01-06T09:15:00",
    location: { lat: 37.8299, lng: -122.269 },
    image_url: "/fresh-oysters-on-ice-with-lemon.jpg",
    address: "4500 Shattuck Ave, Oakland, CA 94609",
    neighborhood: "Temescal",
    phone: "(510) 652-9797",
  },
  {
    id: 4,
    restaurant_name: "Aunt Mary's Cafe",
    deal_description:
      "Buy one glass of wine, get one free. Plus 30% off all small plates. Cozy atmosphere in Temescal.",
    original_price: 10.0,
    deal_price: 5.0,
    schedule: {
      days: ["Tuesday", "Wednesday", "Thursday"],
      start_time: "17:00",
      end_time: "19:00",
    },
    vote_count: 29,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx4",
    created_by: "anonymous",
    created_at: "2025-01-05T16:20:00",
    location: { lat: 37.835, lng: -122.2619 },
    image_url: "/wine-glasses-and-cheese-board-cozy-cafe.jpg",
    address: "4640 Telegraph Ave, Oakland, CA 94609",
    neighborhood: "Temescal",
    phone: "(510) 601-5011",
  },
  {
    id: 5,
    restaurant_name: "Tacos Mi Rancho",
    deal_description: "Authentic street tacos for $3 and house margaritas for $4. Can't beat this deal in Fruitvale!",
    original_price: 6.0,
    deal_price: 3.0,
    schedule: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      start_time: "15:00",
      end_time: "18:00",
    },
    vote_count: 51,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx5",
    created_by: "anonymous",
    created_at: "2025-01-04T11:45:00",
    location: { lat: 37.7749, lng: -122.2247 },
    image_url: "/street-tacos-with-margarita-mexican-food.jpg",
    address: "3520 International Blvd, Oakland, CA 94601",
    neighborhood: "Fruitvale",
    phone: "(510) 533-1497",
  },
  {
    id: 6,
    restaurant_name: "Genki Crepes & Mini Mart",
    deal_description: "All sushi rolls 50% off. Fresh fish daily. Popular spot near Piedmont Avenue.",
    original_price: 14.0,
    deal_price: 7.0,
    schedule: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      start_time: "16:30",
      end_time: "18:30",
    },
    vote_count: 34,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx6",
    created_by: "anonymous",
    created_at: "2025-01-03T13:10:00",
    location: { lat: 37.8232, lng: -122.2516 },
    image_url: "/sushi-rolls-platter-fresh-fish.jpg",
    address: "3617 Grand Ave, Oakland, CA 94610",
    neighborhood: "Grand Lake",
    phone: "(510) 452-8896",
  },
  {
    id: 7,
    restaurant_name: "Forge Pizza",
    deal_description: "Giant NY-style pizza slices with any beer for $5. Perfect Jack London Square spot.",
    original_price: 9.0,
    deal_price: 5.0,
    schedule: {
      days: ["Thursday", "Friday", "Saturday"],
      start_time: "15:00",
      end_time: "18:00",
    },
    vote_count: 47,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx7",
    created_by: "anonymous",
    created_at: "2025-01-02T10:30:00",
    location: { lat: 37.7955, lng: -122.273 },
    image_url: "/giant-pizza-slice-new-york-style.jpg",
    address: "66 Franklin St, Oakland, CA 94607",
    neighborhood: "Jack London Square",
    phone: "(510) 268-3000",
  },
  {
    id: 8,
    restaurant_name: "Millennium Restaurant",
    deal_description: "Every Wednesday, take 40% off any bottle of wine. Great selection of natural wines.",
    original_price: 50.0,
    deal_price: 30.0,
    schedule: {
      days: ["Wednesday"],
      start_time: "17:00",
      end_time: "22:00",
    },
    vote_count: 23,
    google_place_id: "ChIJVVVVVVV5hYARxxxxxxxx8",
    created_by: "anonymous",
    created_at: "2025-01-01T15:00:00",
    location: { lat: 37.8044, lng: -122.2711 },
    image_url: "/natural-wine-bottles-elegant-restaurant.jpg",
    address: "5912 College Ave, Oakland, CA 94618",
    neighborhood: "Rockridge",
    phone: "(510) 735-9459",
  },
]

export const SAMPLE_COMMENTS = [
  // Drake's Dealership (id: 1)
  {
    id: 1,
    deal_id: 1,
    comment_text: "Best happy hour in Oakland! The beer selection is amazing and the vibe is perfect.",
    vote_count: 24,
    created_by: "anonymous",
    created_at: "2025-01-08T10:00:00",
  },
  {
    id: 2,
    deal_id: 1,
    comment_text: "Gets crowded around 5pm but totally worth it. Go early!",
    vote_count: 18,
    created_by: "anonymous",
    created_at: "2025-01-07T14:30:00",
  },
  {
    id: 3,
    deal_id: 1,
    comment_text: "Pro tip: try the IPA flight, you won't regret it.",
    vote_count: 12,
    created_by: "anonymous",
    created_at: "2025-01-06T09:15:00",
  },
  // Lost & Found (id: 2)
  {
    id: 4,
    deal_id: 2,
    comment_text: "The view of Lake Merritt from the patio is stunning during sunset!",
    vote_count: 31,
    created_by: "anonymous",
    created_at: "2025-01-07T18:00:00",
  },
  {
    id: 5,
    deal_id: 2,
    comment_text: "Cocktails are delicious and the truffle fries are a must-try.",
    vote_count: 15,
    created_by: "anonymous",
    created_at: "2025-01-06T16:30:00",
  },
  // The Kebabery (id: 3)
  {
    id: 6,
    deal_id: 3,
    comment_text: "Fresh oysters every time. This is the best deal in the entire city.",
    vote_count: 45,
    created_by: "anonymous",
    created_at: "2025-01-08T12:00:00",
  },
  {
    id: 7,
    deal_id: 3,
    comment_text: "Can't believe they're only $1. The quality is incredible!",
    vote_count: 38,
    created_by: "anonymous",
    created_at: "2025-01-05T14:20:00",
  },
  {
    id: 8,
    deal_id: 3,
    comment_text: "Pairs perfectly with their Sauvignon Blanc.",
    vote_count: 22,
    created_by: "anonymous",
    created_at: "2025-01-04T19:45:00",
  },
  // Aunt Mary's Cafe (id: 4)
  {
    id: 9,
    deal_id: 4,
    comment_text: "Hidden gem in Temescal. Cozy atmosphere and friendly staff.",
    vote_count: 19,
    created_by: "anonymous",
    created_at: "2025-01-07T20:00:00",
  },
  {
    id: 10,
    deal_id: 4,
    comment_text: "The charcuterie board is amazing with the wine deal!",
    vote_count: 14,
    created_by: "anonymous",
    created_at: "2025-01-06T17:15:00",
  },
  {
    id: 11,
    deal_id: 4,
    comment_text: "Great date night spot without breaking the bank.",
    vote_count: 9,
    created_by: "anonymous",
    created_at: "2025-01-05T18:30:00",
  },
  // Tacos Mi Rancho (id: 5)
  {
    id: 12,
    deal_id: 5,
    comment_text: "Authentic Mexican food at unbeatable prices. The carnitas are incredible!",
    vote_count: 41,
    created_by: "anonymous",
    created_at: "2025-01-08T15:30:00",
  },
  {
    id: 13,
    deal_id: 5,
    comment_text: "Margaritas are strong and delicious. Best deal in Fruitvale!",
    vote_count: 28,
    created_by: "anonymous",
    created_at: "2025-01-07T16:00:00",
  },
  {
    id: 14,
    deal_id: 5,
    comment_text: "Always busy but service is fast. Cash only FYI.",
    vote_count: 16,
    created_by: "anonymous",
    created_at: "2025-01-06T14:45:00",
  },
  // Genki Crepes & Mini Mart (id: 6)
  {
    id: 15,
    deal_id: 6,
    comment_text: "Fresh sushi at half price? Yes please! The salmon roll is my favorite.",
    vote_count: 27,
    created_by: "anonymous",
    created_at: "2025-01-07T17:30:00",
  },
  {
    id: 16,
    deal_id: 6,
    comment_text: "Quality is consistently good. Great spot near Piedmont Ave.",
    vote_count: 21,
    created_by: "anonymous",
    created_at: "2025-01-05T16:00:00",
  },
  {
    id: 17,
    deal_id: 6,
    comment_text: "Try the spicy tuna roll - it's fire!",
    vote_count: 13,
    created_by: "anonymous",
    created_at: "2025-01-04T18:20:00",
  },
  // Forge Pizza (id: 7)
  {
    id: 18,
    deal_id: 7,
    comment_text: "Huge slices! One slice is basically a meal. Great waterfront location.",
    vote_count: 36,
    created_by: "anonymous",
    created_at: "2025-01-08T13:15:00",
  },
  {
    id: 19,
    deal_id: 7,
    comment_text: "Perfect after-work spot by the water. Love the pepperoni.",
    vote_count: 25,
    created_by: "anonymous",
    created_at: "2025-01-06T15:45:00",
  },
  {
    id: 20,
    deal_id: 7,
    comment_text: "Beer selection is solid and pairs well with the pizza.",
    vote_count: 17,
    created_by: "anonymous",
    created_at: "2025-01-05T17:30:00",
  },
  // Millennium Restaurant (id: 8)
  {
    id: 21,
    deal_id: 8,
    comment_text: "Natural wine selection is incredible. Worth the Wednesday trip!",
    vote_count: 20,
    created_by: "anonymous",
    created_at: "2025-01-07T19:30:00",
  },
  {
    id: 22,
    deal_id: 8,
    comment_text: "Great vegan food too. The mushroom risotto is amazing.",
    vote_count: 11,
    created_by: "anonymous",
    created_at: "2025-01-06T18:00:00",
  },
  {
    id: 23,
    deal_id: 8,
    comment_text: "Staff is super knowledgeable about the wines.",
    vote_count: 7,
    created_by: "anonymous",
    created_at: "2025-01-04T20:15:00",
  },
]
